--
-- PostgreSQL database dump
--

\restrict w1eG3vGhg1UUeQqqQ9MHHnbvyY5rzeNinGeKiwhgOkABrAbl0rc3is7XUVWzzgh

-- Dumped from database version 18.4 (Homebrew)
-- Dumped by pg_dump version 18.4 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: capitol; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.capitol (
    id integer NOT NULL,
    address text,
    latitude numeric(9,6),
    longitude numeric(9,6),
    capitol_num integer,
    highlight text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.capitol OWNER TO joelkarie;

--
-- Name: capitol_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.capitol ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.capitol_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: city_details; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.city_details (
    location_id integer NOT NULL,
    census_name text,
    population integer,
    is_city_capital boolean
);


ALTER TABLE public.city_details OWNER TO joelkarie;

--
-- Name: digs; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.digs (
    id integer NOT NULL,
    address text,
    latitude numeric(9,6),
    longitude numeric(9,6),
    digs_type_id integer,
    company_housing boolean,
    price_per_night numeric(10,2),
    notes text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.digs OWNER TO joelkarie;

--
-- Name: digs_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.digs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.digs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: digs_type; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.digs_type (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.digs_type OWNER TO joelkarie;

--
-- Name: digs_type_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.digs_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.digs_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotel_brand; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.hotel_brand (
    id integer NOT NULL,
    name text NOT NULL,
    hotel_holding_company_id integer
);


ALTER TABLE public.hotel_brand OWNER TO joelkarie;

--
-- Name: hotel_brand_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.hotel_brand ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotel_brand_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hotel_details; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.hotel_details (
    digs_id integer NOT NULL,
    hotel_brand_id integer
);


ALTER TABLE public.hotel_details OWNER TO joelkarie;

--
-- Name: hotel_holding_company; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.hotel_holding_company (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.hotel_holding_company OWNER TO joelkarie;

--
-- Name: hotel_holding_company_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.hotel_holding_company ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.hotel_holding_company_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.location (
    id integer NOT NULL,
    name text NOT NULL,
    alternative_name text,
    location_type_id integer NOT NULL,
    latitude numeric(9,6),
    longitude numeric(9,6),
    state_province text,
    country text NOT NULL,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.location OWNER TO joelkarie;

--
-- Name: location_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.location ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location_media; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.location_media (
    id integer NOT NULL,
    location_id integer NOT NULL,
    media_type_id integer NOT NULL,
    url text NOT NULL,
    caption text
);


ALTER TABLE public.location_media OWNER TO joelkarie;

--
-- Name: location_media_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.location_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: location_rating; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.location_rating (
    location_id integer NOT NULL,
    joel_could_live boolean,
    michael_could_live boolean,
    highlight text,
    notes text
);


ALTER TABLE public.location_rating OWNER TO joelkarie;

--
-- Name: location_type; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.location_type (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.location_type OWNER TO joelkarie;

--
-- Name: location_type_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.location_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.location_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: media_type; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.media_type (
    id integer NOT NULL,
    name text NOT NULL
);


ALTER TABLE public.media_type OWNER TO joelkarie;

--
-- Name: media_type_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.media_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.media_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: national_park_details; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.national_park_details (
    location_id integer NOT NULL,
    park_visit_num integer
);


ALTER TABLE public.national_park_details OWNER TO joelkarie;

--
-- Name: theatre; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.theatre (
    id integer NOT NULL,
    name text NOT NULL,
    address text,
    latitude numeric(9,6),
    longitude numeric(9,6),
    dresser text,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.theatre OWNER TO joelkarie;

--
-- Name: theatre_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.theatre ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.theatre_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: visit; Type: TABLE; Schema: public; Owner: joelkarie
--

CREATE TABLE public.visit (
    id integer NOT NULL,
    date date,
    original_stop_number integer,
    location_id integer NOT NULL,
    digs_id integer,
    theatre_id integer,
    capitol_id integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.visit OWNER TO joelkarie;

--
-- Name: visit_id_seq; Type: SEQUENCE; Schema: public; Owner: joelkarie
--

ALTER TABLE public.visit ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.visit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: capitol; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.capitol (id, address, latitude, longitude, capitol_num, highlight, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: city_details; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.city_details (location_id, census_name, population, is_city_capital) FROM stdin;
\.


--
-- Data for Name: digs; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.digs (id, address, latitude, longitude, digs_type_id, company_housing, price_per_night, notes, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: digs_type; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.digs_type (id, name) FROM stdin;
1	hotel
2	airbnb
3	boat
4	camping
5	furnished_finder
6	home
7	hostel
\.


--
-- Data for Name: hotel_brand; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.hotel_brand (id, name, hotel_holding_company_id) FROM stdin;
\.


--
-- Data for Name: hotel_details; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.hotel_details (digs_id, hotel_brand_id) FROM stdin;
\.


--
-- Data for Name: hotel_holding_company; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.hotel_holding_company (id, name) FROM stdin;
1	Marriott
2	IHG
3	Sonesta
4	Hiton
5	Hyatt
6	McMenamins
14	Sonder
15	Landing
\.


--
-- Data for Name: location; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.location (id, name, alternative_name, location_type_id, latitude, longitude, state_province, country, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: location_media; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.location_media (id, location_id, media_type_id, url, caption) FROM stdin;
\.


--
-- Data for Name: location_rating; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.location_rating (location_id, joel_could_live, michael_could_live, highlight, notes) FROM stdin;
\.


--
-- Data for Name: location_type; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.location_type (id, name) FROM stdin;
1	city
2	national_park
3	landmark
4	home
\.


--
-- Data for Name: media_type; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.media_type (id, name) FROM stdin;
1	manhole_photo
\.


--
-- Data for Name: national_park_details; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.national_park_details (location_id, park_visit_num) FROM stdin;
\.


--
-- Data for Name: theatre; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.theatre (id, name, address, latitude, longitude, dresser, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: visit; Type: TABLE DATA; Schema: public; Owner: joelkarie
--

COPY public.visit (id, date, original_stop_number, location_id, digs_id, theatre_id, capitol_id, created_at, updated_at) FROM stdin;
\.


--
-- Name: capitol_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.capitol_id_seq', 1, false);


--
-- Name: digs_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.digs_id_seq', 1, false);


--
-- Name: digs_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.digs_type_id_seq', 7, true);


--
-- Name: hotel_brand_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.hotel_brand_id_seq', 1, false);


--
-- Name: hotel_holding_company_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.hotel_holding_company_id_seq', 15, true);


--
-- Name: location_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.location_id_seq', 1, false);


--
-- Name: location_media_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.location_media_id_seq', 1, false);


--
-- Name: location_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.location_type_id_seq', 9, true);


--
-- Name: media_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.media_type_id_seq', 1, true);


--
-- Name: theatre_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.theatre_id_seq', 1, false);


--
-- Name: visit_id_seq; Type: SEQUENCE SET; Schema: public; Owner: joelkarie
--

SELECT pg_catalog.setval('public.visit_id_seq', 1, false);


--
-- Name: capitol capitol_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.capitol
    ADD CONSTRAINT capitol_pkey PRIMARY KEY (id);


--
-- Name: city_details city_details_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.city_details
    ADD CONSTRAINT city_details_pkey PRIMARY KEY (location_id);


--
-- Name: digs digs_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.digs
    ADD CONSTRAINT digs_pkey PRIMARY KEY (id);


--
-- Name: digs_type digs_type_name_key; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.digs_type
    ADD CONSTRAINT digs_type_name_key UNIQUE (name);


--
-- Name: digs_type digs_type_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.digs_type
    ADD CONSTRAINT digs_type_pkey PRIMARY KEY (id);


--
-- Name: hotel_brand hotel_brand_name_key; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.hotel_brand
    ADD CONSTRAINT hotel_brand_name_key UNIQUE (name);


--
-- Name: hotel_brand hotel_brand_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.hotel_brand
    ADD CONSTRAINT hotel_brand_pkey PRIMARY KEY (id);


--
-- Name: hotel_details hotel_details_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.hotel_details
    ADD CONSTRAINT hotel_details_pkey PRIMARY KEY (digs_id);


--
-- Name: hotel_holding_company hotel_holding_company_name_key; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.hotel_holding_company
    ADD CONSTRAINT hotel_holding_company_name_key UNIQUE (name);


--
-- Name: hotel_holding_company hotel_holding_company_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.hotel_holding_company
    ADD CONSTRAINT hotel_holding_company_pkey PRIMARY KEY (id);


--
-- Name: location_media location_media_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.location_media
    ADD CONSTRAINT location_media_pkey PRIMARY KEY (id);


--
-- Name: location location_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_pkey PRIMARY KEY (id);


--
-- Name: location_rating location_rating_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.location_rating
    ADD CONSTRAINT location_rating_pkey PRIMARY KEY (location_id);


--
-- Name: location_type location_type_name_key; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.location_type
    ADD CONSTRAINT location_type_name_key UNIQUE (name);


--
-- Name: location_type location_type_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.location_type
    ADD CONSTRAINT location_type_pkey PRIMARY KEY (id);


--
-- Name: media_type media_type_name_key; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.media_type
    ADD CONSTRAINT media_type_name_key UNIQUE (name);


--
-- Name: media_type media_type_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.media_type
    ADD CONSTRAINT media_type_pkey PRIMARY KEY (id);


--
-- Name: national_park_details national_park_details_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.national_park_details
    ADD CONSTRAINT national_park_details_pkey PRIMARY KEY (location_id);


--
-- Name: theatre theatre_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.theatre
    ADD CONSTRAINT theatre_pkey PRIMARY KEY (id);


--
-- Name: visit visit_pkey; Type: CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.visit
    ADD CONSTRAINT visit_pkey PRIMARY KEY (id);


--
-- Name: city_details city_details_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.city_details
    ADD CONSTRAINT city_details_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.location(id) DEFERRABLE;


--
-- Name: digs digs_digs_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.digs
    ADD CONSTRAINT digs_digs_type_id_fkey FOREIGN KEY (digs_type_id) REFERENCES public.digs_type(id) DEFERRABLE;


--
-- Name: hotel_brand hotel_brand_hotel_holding_company_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.hotel_brand
    ADD CONSTRAINT hotel_brand_hotel_holding_company_id_fkey FOREIGN KEY (hotel_holding_company_id) REFERENCES public.hotel_holding_company(id) DEFERRABLE;


--
-- Name: hotel_details hotel_details_digs_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.hotel_details
    ADD CONSTRAINT hotel_details_digs_id_fkey FOREIGN KEY (digs_id) REFERENCES public.digs(id) DEFERRABLE;


--
-- Name: hotel_details hotel_details_hotel_brand_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.hotel_details
    ADD CONSTRAINT hotel_details_hotel_brand_id_fkey FOREIGN KEY (hotel_brand_id) REFERENCES public.hotel_brand(id) DEFERRABLE;


--
-- Name: location location_location_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.location
    ADD CONSTRAINT location_location_type_id_fkey FOREIGN KEY (location_type_id) REFERENCES public.location_type(id) DEFERRABLE;


--
-- Name: location_media location_media_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.location_media
    ADD CONSTRAINT location_media_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.location(id) DEFERRABLE;


--
-- Name: location_media location_media_media_type_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.location_media
    ADD CONSTRAINT location_media_media_type_id_fkey FOREIGN KEY (media_type_id) REFERENCES public.media_type(id) DEFERRABLE;


--
-- Name: location_rating location_rating_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.location_rating
    ADD CONSTRAINT location_rating_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.location(id) DEFERRABLE;


--
-- Name: national_park_details national_park_details_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.national_park_details
    ADD CONSTRAINT national_park_details_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.location(id) DEFERRABLE;


--
-- Name: visit visit_capitol_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.visit
    ADD CONSTRAINT visit_capitol_id_fkey FOREIGN KEY (capitol_id) REFERENCES public.capitol(id) DEFERRABLE;


--
-- Name: visit visit_digs_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.visit
    ADD CONSTRAINT visit_digs_id_fkey FOREIGN KEY (digs_id) REFERENCES public.digs(id) DEFERRABLE;


--
-- Name: visit visit_location_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.visit
    ADD CONSTRAINT visit_location_id_fkey FOREIGN KEY (location_id) REFERENCES public.location(id) DEFERRABLE;


--
-- Name: visit visit_theatre_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: joelkarie
--

ALTER TABLE ONLY public.visit
    ADD CONSTRAINT visit_theatre_id_fkey FOREIGN KEY (theatre_id) REFERENCES public.theatre(id) DEFERRABLE;


--
-- PostgreSQL database dump complete
--

\unrestrict w1eG3vGhg1UUeQqqQ9MHHnbvyY5rzeNinGeKiwhgOkABrAbl0rc3is7XUVWzzgh

