CREATE TABLE "visit" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "date" date,
  "visit_order" integer,
  "original_stop_number" integer,
  "location_id" integer NOT NULL,
  "digs_id" integer,
  "theatre_id" integer,
  "capitol_id" integer,
  "housing_distance" numeric,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now()),

  CONSTRAINT visit_unique_date_location
    UNIQUE (date, location_id)
);

CREATE TABLE "location" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "census_name" text,
  "alternative_name" text,
  "location_type_id" integer NOT NULL,
  "latitude" numeric(9,6),
  "longitude" numeric(9,6),
  "state_province" text,
  "country" text NOT NULL,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now()),

  CONSTRAINT unique_location
    UNIQUE (name, state_province, country)
);

CREATE TABLE "location_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "national_park_details" (
  "location_id" integer PRIMARY KEY,
  "park_visit_num" integer
);

CREATE TABLE "city_details" (
  "location_id" integer PRIMARY KEY,
  "population" integer,
  "is_city_capital" bool
);

CREATE TABLE "location_rating" (
  "location_id" integer PRIMARY KEY,
  "joel_could_live" bool,
  "michael_could_live" bool,
  "highlight" text,
  "notes" text
);

CREATE TABLE "location_media" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location_id" integer NOT NULL,
  "media_type_id" integer NOT NULL,
  "url" text NOT NULL,
  "caption" text
);

CREATE TABLE "media_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "capitol" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text,
  "address" text,
  "country" text,
  "latitude" numeric(9,6),
  "longitude" numeric(9,6),
  "capitol_num" integer,
  "year_completed" text,
  "architect" text,
  "architectural_style" text,
  "size_sq_ft" numeric,
  "dome_height" text,
  "fact" text,
  "highlight" text,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "theatre" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text NOT NULL,
  "address" text,
  "latitude" numeric(9,6),
  "longitude" numeric(9,6),
  "dresser" text,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now()),

  CONSTRAINT unique_theatre
    UNIQUE (name, address)
);

CREATE TABLE "digs" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "address" text,
  "latitude" numeric(9,6),
  "longitude" numeric(9,6),
  "digs_type_id" integer,
  "company_housing" bool,
  "price_per_night" numeric(10,2),
  "notes" text,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now()),

  CONSTRAINT unique_digs
    UNIQUE (address)
);

CREATE TABLE "digs_type" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "hotel_details" (
  "digs_id" integer PRIMARY KEY,
  "hotel_brand_id" integer
);

CREATE TABLE "hotel_holding_company" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL
);

CREATE TABLE "hotel_brand" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" text UNIQUE NOT NULL,
  "hotel_holding_company_id" integer
);

CREATE TABLE "housing_calculations" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "digs_id" integer,
  "total_paid_personal" numeric(10,2),
  "total_company_paid" numeric(10,2),
  "total_days_stayed" integer,
  "daily_cost" numeric(10,2),
  "daily_buyout" numeric(10,2),
  "daily_housing_buyout" numeric(10,2),
  "other_stay" numeric(10,2),
  "total_spent" numeric(10,2),
  "weeks" integer,
  "combined_weekly_buyout" numeric(10,2),
  "housing_buyout" numeric(10,2),
  "housing_savings" numeric(10,2)
);

/*
TODO: housing_calculations should eventually use internal calculations instead of so many variables.
All of the calculations should be possible using:
City, State, Weeks, Date, On Our Own, Company Housing Nights, Daily Buyout, Total Paid, Other Stay Payments.

*/

ALTER TABLE "visit" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "visit" ADD FOREIGN KEY ("digs_id") REFERENCES "digs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "visit" ADD FOREIGN KEY ("theatre_id") REFERENCES "theatre" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "visit" ADD FOREIGN KEY ("capitol_id") REFERENCES "capitol" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location" ADD FOREIGN KEY ("location_type_id") REFERENCES "location_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "national_park_details" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "city_details" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_rating" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_media" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "location_media" ADD FOREIGN KEY ("media_type_id") REFERENCES "media_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "digs" ADD FOREIGN KEY ("digs_type_id") REFERENCES "digs_type" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "hotel_details" ADD FOREIGN KEY ("digs_id") REFERENCES "digs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "hotel_details" ADD FOREIGN KEY ("hotel_brand_id") REFERENCES "hotel_brand" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "hotel_brand" ADD FOREIGN KEY ("hotel_holding_company_id") REFERENCES "hotel_holding_company" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "housing_calculations" ADD FOREIGN KEY ("digs_id") REFERENCES "digs" ("id") DEFERRABLE INITIALLY IMMEDIATE;

DROP TABLE IF EXISTS paradise_voyage_raw_import;

CREATE TABLE paradise_voyage_raw_import (
    "Visit Number" text,
    "Visit Order" text,
    "City" text,
    "State/Province" text,
    "Country" text,
    "Latitude" text,
    "Longitude" text,
    "Year Visited" text, -- Not used (not necessary, TODO drop)
    "Visit Date" text,
    "Location Type" text,
    "Census Name" text, -- Not used
    "Capitol" text, -- Not used
    "Capitol Num" text, -- Not used
    "Number of Visits" text, -- Not used
    "Tour Stop" text, -- Not Used
    "Theatre" text,
    "Theatre Address" text,
    "Theatre Lat" text,
    "Theatre Lon" text,
    "Company Housing" text,
    "Digs" text,
    "Hotel Holding" text,
    "Hotel Brand" text,
    "Digs Address" text,
    "Digs Lat" text,
    "Digs Lon" text,
    "Housing Dist" text,
    "Num Hotels" text, -- Not used (Not necessary?)
    "Joel Could Live" text,
    "Michael Could Live" text,
    "Highlight" text,
    "Original Stop Number" text,
    "AKA" text,
    "Manhole" text,
    "Population" text
);

DROP TABLE IF EXISTS us_capitol_raw_import;

CREATE TABLE us_capitol_raw_import (
    "State" text,
    "Capitol Address" text,
    "Year Completed" text,
    "Architect" text,
    "Architectural Style" text,
    "Approximate Size (sq ft)" text,
    "Dome Height" text,
    "Trivia Fact" text,
    "Latitude" text,
    "Longitude" text
);

DROP TABLE IF EXISTS canadian_legislative_buildings_import;

CREATE TABLE canadian_legislative_buildings_import (
    "Province/Territory" text,
    "Capital" text,
    "Legislative Building" text,
    "Address" text,
    "Year Completed" text,
    "Architect" text,
    "Architectural Style" text,
    "Approximate Size (sq ft)" text,
    "Height / Dome Height" text,
    "Heritage Designation" text,
    "Trivia Fact" text,
    "Latitude" text,
    "Longitude" text
);

CREATE TABLE tour_housing_calculation_import (
  "City" text,
  "State/Province" text,
  "Total Digs Paid" text,
  "Company Housing Days" text,
  "Company Paid" text,
  "Total Stayed" text,
  "Daily Cost" text,
  "Daily Buyout" text,
  "Per Diem" text,
  "Daily Housing Buyout" text,
  "Weekly Buyout" text,
  "Other Stay" text,
  "Total Spent" text,
  "Weeks" text,
  "Total Buyout" text, -- Total buyout for the week with housing and per diem
  "Housing Buyout" text,
  "Housing Savings" text,
  "Weekly Savings" text,
  "Order" text,
  "Year" text
)
